apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-bugs-list-1
data:
  bugs_list.txt: |
    Closure 36
    Closure 37
    Closure 38
    Closure 39
    Closure 40
    Closure 41
    Closure 42
    Closure 43
    Closure 44
    Closure 45
    Closure 46
    Closure 47
    Closure 48
    Closure 49
    Closure 50
    Closure 51
    Closure 52
    Closure 53
    Closure 54
    Closure 55
    Closure 56
    Closure 57
    Closure 58
    Closure 59
    Closure 60
    Closure 61
    Closure 62
    Closure 64
    Closure 65
    Closure 66
    Closure 67
    Closure 68
    Closure 69
    Closure 70
    Closure 71
    Closure 72
    Closure 73
    Closure 74
    Closure 75
    Closure 76
    Closure 77
    Closure 78
    Closure 79
    Closure 80
    Closure 81
    Closure 82
    Closure 83
    Closure 84
    Closure 85
    Closure 86
    Closure 87
    Closure 88
    Closure 89
    Closure 90
    Closure 91
    Closure 92
    Closure 94
    Closure 95
    Closure 96
    Closure 97
    Closure 98
    Closure 99
    Closure 100
    Closure 101
    Closure 102
    Closure 103
    Closure 104
    Closure 105
    Closure 106
    Closure 107
    Closure 108
    Closure 109
    Closure 110
    Closure 111
    Closure 112
    Closure 113
    Closure 114
    Closure 115
    Closure 116
    Closure 117
    Closure 118
    Closure 119
    Closure 120
    Closure 121
    Closure 122
    Closure 123
    Closure 124
    Closure 125
    Closure 126
    Closure 127
    Closure 128
    Closure 129
    Closure 130
    Closure 131
    Closure 132
    Closure 133
    Closure 134
    Closure 135
    Closure 136
    Closure 137