apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-bugs-list-10
data:
  bugs_list.txt: |
    Closure 1
    Closure 5
    Closure 13
    Closure 15
    Closure 32
    Closure 53
    Closure 57
    Closure 59
    Closure 60
    Closure 61
    Closure 65
    Closure 69
    Closure 73
    Closure 81
    Closure 84
    Closure 116
    Closure 118
    Closure 119
    Closure 164
    Closure 172
    Codec 12
    Collections 27
    Compress 9
    JacksonDatabind 31
    JacksonDatabind 54
    JacksonDatabind 63
    JacksonDatabind 67
    JacksonDatabind 70
    JacksonDatabind 74
    JacksonDatabind 76
    JacksonDatabind 78
    JacksonDatabind 80
    JacksonDatabind 81
    JacksonDatabind 82
    JacksonDatabind 83
    JacksonDatabind 84
    JacksonDatabind 85
    JacksonDatabind 86
    JacksonDatabind 87
    JacksonDatabind 88
    JacksonDatabind 90
    JacksonDatabind 91
    JacksonDatabind 93
    JacksonDatabind 95
    JacksonDatabind 96
    JacksonDatabind 97
    JacksonDatabind 98
    JacksonDatabind 99
    JacksonDatabind 100
    JacksonDatabind 101
    JacksonDatabind 102
    JacksonDatabind 103
    JacksonDatabind 104
    JacksonDatabind 105
    JacksonDatabind 106
    JacksonDatabind 107
    JacksonDatabind 108
    JacksonDatabind 109
    JacksonDatabind 110
    JacksonDatabind 111
    JacksonDatabind 112
    Jsoup 5
    Jsoup 49
    Jsoup 51
    Lang 5
    Lang 6
    Math 5
    Math 9
    Math 24
    Math 57
    Math 94
    Math 99
    Mockito 1
    Mockito 8
    Csv 8
    JacksonCore 5