apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-bugs-list-3
data:
  bugs_list.txt: |
    Closure 138
    Closure 139
    Closure 140
    Closure 141
    Closure 142
    Closure 143
    Closure 144
    Closure 145
    Closure 146
    Closure 147
    Closure 148
    Closure 149
    Closure 150
    Closure 151
    Closure 152
    Closure 153
    Closure 154
    Closure 155
    Closure 156
    Closure 157
    Closure 158
    Closure 159
    Closure 160
    Closure 161
    Closure 162
    Closure 163
    Closure 164
    Closure 165
    Closure 166
    Closure 167
    Closure 168
    Closure 169
    Closure 170
    Closure 171
    Closure 172
    Closure 173
    Closure 174
    Closure 175
    Closure 176
    Codec 1
    Codec 2
    Codec 3
    Codec 4
    Codec 5
    Codec 6
    Codec 7
    Codec 8
    Codec 9
    Codec 10
    Codec 11
    Codec 12
    Codec 13
    Codec 14
    Codec 15
    Codec 16
    Codec 17
    Codec 18
    Collections 1
    Collections 2
    Collections 3
    Collections 4
    Collections 5
    Collections 6
    Collections 7
    Collections 8
    Collections 9
    Collections 10
    Collections 11
    Collections 12
    Collections 13
    Collections 14
    Collections 15
    Collections 16
    Collections 17
    Collections 18
    Collections 19
    Collections 20
    Collections 21
    Collections 22
    Collections 23
    Collections 24
    Collections 25
    Collections 26
    Collections 27
    Collections 28
    Compress 1
    Compress 2
    Compress 3
    Compress 4
    Compress 5
    Compress 6
    Compress 7
    Compress 8
    Compress 9
    Compress 10
    Compress 11
    Compress 12
    Compress 13
    Compress 14
    Compress 15