apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-bugs-list-4
data:
  bugs_list.txt: |
    JacksonDatabind 9
    JacksonDatabind 10
    JacksonDatabind 11
    JacksonDatabind 12
    JacksonDatabind 13
    JacksonDatabind 14
    JacksonDatabind 15
    JacksonDatabind 16
    JacksonDatabind 17
    JacksonDatabind 18
    JacksonDatabind 19
    JacksonDatabind 20
    JacksonDatabind 21
    JacksonDatabind 22
    JacksonDatabind 23
    JacksonDatabind 24
    JacksonDatabind 25
    JacksonDatabind 26
    JacksonDatabind 27
    JacksonDatabind 28
    JacksonDatabind 29
    JacksonDatabind 30
    JacksonDatabind 31
    JacksonDatabind 32
    JacksonDatabind 33
    JacksonDatabind 34
    JacksonDatabind 35
    JacksonDatabind 36
    JacksonDatabind 37
    JacksonDatabind 38
    JacksonDatabind 39
    JacksonDatabind 40
    JacksonDatabind 41
    JacksonDatabind 42
    JacksonDatabind 43
    JacksonDatabind 44
    JacksonDatabind 45
    JacksonDatabind 46
    JacksonDatabind 47
    JacksonDatabind 48
    JacksonDatabind 49
    JacksonDatabind 50
    JacksonDatabind 51
    JacksonDatabind 52
    JacksonDatabind 53
    JacksonDatabind 54
    JacksonDatabind 55
    JacksonDatabind 56
    JacksonDatabind 57
    JacksonDatabind 58
    JacksonDatabind 59
    JacksonDatabind 60
    JacksonDatabind 61
    JacksonDatabind 62
    JacksonDatabind 63
    JacksonDatabind 64
    JacksonDatabind 66
    JacksonDatabind 67
    JacksonDatabind 68
    JacksonDatabind 69
    JacksonDatabind 70
    JacksonDatabind 71
    JacksonDatabind 72
    JacksonDatabind 73
    JacksonDatabind 74
    JacksonDatabind 75
    JacksonDatabind 76
    JacksonDatabind 77
    JacksonDatabind 78
    JacksonDatabind 79
    JacksonDatabind 80
    JacksonDatabind 81
    JacksonDatabind 82
    JacksonDatabind 83
    JacksonDatabind 84
    JacksonDatabind 85
    JacksonDatabind 86
    JacksonDatabind 87
    JacksonDatabind 88
    JacksonDatabind 90
    JacksonDatabind 91
    JacksonDatabind 92
    JacksonDatabind 93
    JacksonDatabind 94
    JacksonDatabind 95
    JacksonDatabind 96
    JacksonDatabind 97
    JacksonDatabind 98
    JacksonDatabind 99
    JacksonDatabind 100
    JacksonDatabind 101
    JacksonDatabind 102
    JacksonDatabind 103
    JacksonDatabind 104
    JacksonDatabind 105
    JacksonDatabind 106
    JacksonDatabind 107
    JacksonDatabind 108
    JacksonDatabind 109
    JacksonDatabind 110