apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-bugs-list-5
data:
  bugs_list.txt: |
    JacksonDatabind 111
    JacksonDatabind 112
    JacksonXml 1
    JacksonXml 2
    JacksonXml 3
    JacksonXml 4
    JacksonXml 5
    JacksonXml 6
    Jsoup 1
    Jsoup 2
    Jsoup 3
    Jsoup 4
    Jsoup 5
    Jsoup 6
    Jsoup 7
    Jsoup 8
    Jsoup 9
    Jsoup 10
    Jsoup 11
    Jsoup 12
    Jsoup 13
    Jsoup 14
    Jsoup 15
    Jsoup 16
    Jsoup 17
    Jsoup 18
    Jsoup 19
    Jsoup 20
    Jsoup 21
    Jsoup 22
    Jsoup 23
    Jsoup 24
    Jsoup 25
    Jsoup 26
    Jsoup 27
    Jsoup 28
    Jsoup 29
    Jsoup 30
    Jsoup 31
    Jsoup 32
    Jsoup 33
    Jsoup 34
    Jsoup 35
    Jsoup 36
    Jsoup 37
    Jsoup 38
    Jsoup 39
    Jsoup 40
    Jsoup 41
    Jsoup 42
    Jsoup 43
    Jsoup 44
    Jsoup 45
    Jsoup 46
    Jsoup 47
    Jsoup 48
    Jsoup 49
    Jsoup 50
    Jsoup 51
    Jsoup 52
    Jsoup 53
    Jsoup 54
    Jsoup 55
    Jsoup 56
    Jsoup 57
    Jsoup 58
    Jsoup 59
    Jsoup 60
    Jsoup 61
    Jsoup 62
    Jsoup 63
    Jsoup 64
    Jsoup 65
    Jsoup 66
    Jsoup 67
    Jsoup 68
    Jsoup 69
    Jsoup 70
    Jsoup 71
    Jsoup 72
    Jsoup 73
    Jsoup 74
    Jsoup 75
    Jsoup 76
    Jsoup 77
    Jsoup 78
    Jsoup 79
    Jsoup 80
    Jsoup 81
    Jsoup 82
    Jsoup 83
    Jsoup 84
    Jsoup 85
    Jsoup 86
    Jsoup 87
    Jsoup 88
    Jsoup 89
    Jsoup 90
    Jsoup 91