apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-bugs-list-6
data:
  bugs_list.txt: |
    Jsoup 92
    Jsoup 93
    JxPath 1
    JxPath 2
    JxPath 3
    JxPath 4
    JxPath 5
    JxPath 6
    JxPath 7
    JxPath 8
    JxPath 9
    JxPath 10
    JxPath 11
    JxPath 12
    JxPath 13
    JxPath 14
    JxPath 15
    JxPath 16
    JxPath 17
    JxPath 18
    JxPath 19
    JxPath 20
    JxPath 21
    JxPath 22
    Lang 1
    Lang 3
    Lang 4
    Lang 5
    Lang 6
    Lang 7
    Lang 8
    Lang 9
    Lang 10
    Lang 11
    Lang 12
    Lang 13
    Lang 14
    Lang 15
    Lang 16
    Lang 17
    Lang 19
    Lang 20
    Lang 21
    Lang 22
    Lang 23
    Lang 24
    Lang 26
    Lang 27
    Lang 28
    Lang 29
    Lang 30
    Lang 31
    Lang 32
    Lang 33
    Lang 34
    Lang 35
    Lang 36
    Lang 37
    Lang 38
    Lang 39
    Lang 40
    Lang 41
    Lang 42
    Lang 43
    Lang 44
    Lang 45
    Lang 46
    Lang 47
    Lang 49
    Lang 50
    Lang 51
    Lang 52
    Lang 53
    Lang 54
    Lang 55
    Lang 56
    Lang 57
    Lang 58
    Lang 59
    Lang 60
    Lang 61
    Lang 62
    Lang 63
    Lang 64
    Lang 65
    Math 1
    Math 2
    Math 3
    Math 4
    Math 5
    Math 6
    Math 7
    Math 8
    Math 9
    Math 10
    Math 11
    Math 12
    Math 13
    Math 14
    Math 15