apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-bugs-list-7
data:
  bugs_list.txt: |
    Math 16
    Math 17
    Math 18
    Math 19
    Math 20
    Math 21
    Math 22
    Math 23
    Math 24
    Math 25
    Math 26
    Math 27
    Math 28
    Math 29
    Math 30
    Math 31
    Math 32
    Math 33
    Math 34
    Math 35
    Math 36
    Math 37
    Math 38
    Math 39
    Math 40
    Math 41
    Math 42
    Math 43
    Math 44
    Math 45
    Math 46
    Math 47
    Math 48
    Math 49
    Math 50
    Math 51
    Math 52
    Math 53
    Math 54
    Math 55
    Math 56
    Math 57
    Math 58
    Math 59
    Math 60
    Math 61
    Math 62
    Math 63
    Math 64
    Math 65
    Math 66
    Math 67
    Math 68
    Math 69
    Math 70
    Math 71
    Math 72
    Math 73
    Math 74
    Math 75
    Math 76
    Math 77
    Math 78
    Math 79
    Math 80
    Math 81
    Math 82
    Math 83
    Math 84
    Math 85
    Math 86
    Math 87
    Math 88
    Math 89
    Math 90
    Math 91
    Math 92
    Math 93
    Math 94
    Math 95
    Math 96
    Math 97
    Math 98
    Math 99
    Math 100
    Math 101
    Math 102
    Math 103
    Math 104
    Math 105
    Math 106
    Mockito 1
    Mockito 2
    Mockito 3
    Mockito 4
    Mockito 5
    Mockito 6
    Mockito 7
    Mockito 8