apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-bugs-list-8
data:
  bugs_list.txt: |
    Mockito 9
    Mockito 10
    Mockito 11
    Mockito 12
    Mockito 13
    Mockito 14
    Mockito 15
    Mockito 16
    Mockito 17
    Mockito 18
    Mockito 19
    Mockito 20
    Mockito 21
    Mockito 22
    Mockito 23
    Mockito 24
    Mockito 25
    Mockito 26
    Mockito 27
    Mockito 28
    Mockito 29
    Mockito 30
    Mockito 31
    Mockito 32
    Mockito 33
    Mockito 34
    Mockito 35
    Mockito 36
    Mockito 37
    Mockito 38
    Time 1
    Time 2
    Time 3
    Time 4
    Time 5
    Time 6
    Time 7
    Time 8
    Time 9
    Time 10
    Time 11
    Time 12
    Time 13
    Time 14
    Time 15
    Time 16
    Time 17
    Time 18
    Time 19
    Time 20
    Time 22
    Time 23
    Time 24
    Time 25
    Time 26
    Time 27