apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-bugs-list-9
data:
  bugs_list.txt: |
    Compress 16
    Compress 17
    Compress 18
    Compress 19
    Compress 20
    Compress 21
    Compress 22
    Compress 23
    Compress 24
    Compress 25
    Compress 26
    Compress 27
    Compress 28
    Compress 29
    Compress 30
    Compress 31
    Compress 32
    Compress 33
    Compress 34
    Compress 35
    Compress 36
    Compress 37
    Compress 38
    Compress 39
    Compress 40
    Compress 41
    Compress 42
    Compress 43
    Compress 44
    Compress 45
    Compress 46
    Compress 47
    Csv 1
    Csv 2
    Csv 3
    Csv 4
    Csv 5
    Csv 6
    Csv 7
    Csv 8
    Csv 9
    Csv 10
    Csv 11
    Csv 12
    Csv 13
    Csv 14
    Csv 15
    Csv 16
    Gson 1
    Gson 2
    Gson 3
    Gson 4
    Gson 5
    Gson 6
    Gson 7
    Gson 8
    Gson 9
    Gson 10
    Gson 11
    Gson 12
    Gson 13
    Gson 14
    Gson 15
    Gson 16
    Gson 17
    Gson 18
    JacksonCore 1
    JacksonCore 2
    JacksonCore 3
    JacksonCore 4
    JacksonCore 5
    JacksonCore 6
    JacksonCore 7
    JacksonCore 8
    JacksonCore 9
    JacksonCore 10
    JacksonCore 11
    JacksonCore 12
    JacksonCore 13
    JacksonCore 14
    JacksonCore 15
    JacksonCore 16
    JacksonCore 17
    JacksonCore 18
    JacksonCore 19
    JacksonCore 20
    JacksonCore 21
    JacksonCore 22
    JacksonCore 23
    JacksonCore 24
    JacksonCore 25
    JacksonCore 26
    JacksonDatabind 1
    JacksonDatabind 2
    JacksonDatabind 3
    JacksonDatabind 4
    JacksonDatabind 5
    JacksonDatabind 6
    JacksonDatabind 7
    JacksonDatabind 8