apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-bugs-list
data:
  bugs_list.txt: |
    Chart 1
    Chart 2
    Chart 3
    Chart 4
    Chart 5
    Chart 6
    Chart 7
    Chart 8
    Chart 9
    Chart 10
    Chart 11
    Chart 12