apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-bugs-list
data:
  bugs_list.txt: |
    Chart 1
    Chart 2
    Chart 3
    Chart 4
    Chart 5
    Chart 6
    Chart 7
    Chart 8
    Chart 9
    Chart 10
    Chart 11
    Chart 12
    Chart 13
    Chart 14
    Chart 15
    Chart 16
    Chart 17
    Chart 18
    Chart 19
    Chart 20
    Chart 21
    Chart 22
    Chart 23
    Chart 24
    Chart 25
    Chart 26
    Cli 1
    Cli 2
    Cli 3
    Cli 4
    Cli 5
    Cli 7
    Cli 8
    Cli 9
    Cli 10
    Cli 11
    Cli 12
    Cli 13
    Cli 14
    Cli 15
    Cli 16
    Cli 17
    Cli 18
    Cli 19
    Cli 20
    Cli 21
    Cli 22
    Cli 23
    Cli 24
    Cli 25
    Cli 26
    Cli 27
    Cli 28
    Cli 29
    Cli 30
    Cli 31
    Cli 32
    Cli 33
    Cli 34
    Cli 35
    Cli 36
    Cli 37
    Cli 38
    Cli 39
    Cli 40
    Closure 1
    Closure 2
    Closure 3
    Closure 4
    Closure 5
    Closure 6
    Closure 7
    Closure 8
    Closure 9
    Closure 10
    Closure 11
    Closure 12
    Closure 13
    Closure 14
    Closure 15
    Closure 16
    Closure 17
    Closure 18
    Closure 19
    Closure 20
    Closure 21
    Closure 22
    Closure 23
    Closure 24
    Closure 25
    Closure 26
    Closure 27
    Closure 28
    Closure 29
    Closure 30
    Closure 31
    Closure 32
    Closure 33
    Closure 34
    Closure 35